### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#111]
This error threw after a while moving the map and navigating. 

the map goes to grey and can´t reload .

![Captura de Pantalla 2023-04-14 a las 17 28 05](https://user-images.githubusercontent.com/23015314/232087860-d4ade20c-f59a-4ae1-907a-22c2475dee99.jpg)

**Comment by albjeremias** [comment]
no this is an error on loading tiles.. we need to change the tile provider:

import { stamenTerrain } from 'pigeon-maps/providers'; 

to use `osm` instead of `stamenTerrain`

https://github.com/helpbuttons/helpbuttons/blob/main/web/src/components/map/Map/ExploreMap.tsx#L3

https://github.com/helpbuttons/helpbuttons/blob/main/web/src/components/map/Map/MarkerSelectorMap.tsx#L4

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/a8a689342a81502aeec37587b11d6e6dcf0bb5a1
